### ISSUE TITLE
unable to install node-red-vis

### ISSUE THREAD

**Issue by radar50** [GermanBluefox/node-red-vis#20]
Im trying to install node-red-vis but it fail with this message:

npm install node-red-vis --unsafe-perm
[sudo] password for orangepi: 

> iobroker.vis-google-fonts@0.1.0 install /home/orangepi/.node-red/node_modules/iobroker.vis-google-fonts
> node main.js --install

> node-red-vis@0.4.2 install /home/orangepi/.node-red/node_modules/node-red-vis
> node node_modules/iobroker.vis/lib/install.js

module.js:328
    throw err;
    ^

Error: Cannot find module '/home/orangepi/.node-red/node_modules/node-red-vis/node_modules/iobroker.vis/lib/install.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm WARN enoent ENOENT: no such file or directory, open '/home/orangepi/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.
npm ERR! Linux 3.10.65
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "node-red-vis" "--unsafe-perm"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-red-vis@0.4.2 install: `node node_modules/iobroker.vis/lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-vis@0.4.2 install script 'node node_modules/iobroker.vis/lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-vis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/iobroker.vis/lib/install.js

Can you help me please?

**Comment by KukuruzaAndrii** [comment]
Same problem

**Comment by aleqcz** [comment]
Same here. Anyone managed to install it lately?
`npm install node-red-vis

> iobroker.vis@0.10.15 install /home/node/node_modules/iobroker.vis
> node main.js --install


> iobroker.vis-google-fonts@0.1.0 install /home/node/node_modules/iobroker.vis-google-fonts
> node main.js --install


> node-red-vis@0.4.2 install /home/node/node_modules/node-red-vis
> node node_modules/iobroker.vis/lib/install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/home/node/node_modules/node-red-vis/node_modules/iobroker.vis/lib/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm WARN enoent ENOENT: no such file or directory, open '/home/node/package.json'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-vis"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-red-vis@0.4.2 install: `node node_modules/iobroker.vis/lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-vis@0.4.2 install script 'node node_modules/iobroker.vis/lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-vis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/iobroker.vis/lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-vis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-vis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
`
npm-debug.log shared here [http://pasted.co/08c85a2f](url)

**Comment by aleqcz** [comment]
If iobroker.vis is installed manually prior to node-red-vis, the error is different:

```
npm install node-red-vis

> node-red-vis@0.4.2 install /home/node/node_modules/node-red-vis
> node node_modules/iobroker.vis/lib/install.js

Cannot parse "/home/node/node_modules/node-red-vis/node_modules/iobroker.vis/lib/../../../../iobroker.vis-plumb/io-package.json": SyntaxError: Unexpected string in JSON at position 318

> iobroker.vis@0.10.15 install /home/node/node_modules/node-red-vis/node_modules/iobroker.vis
> node main.js --install


> iobroker.vis-google-fonts@0.1.0 install /home/node/node_modules/iobroker.vis-google-fonts
> node main.js --install

npm WARN node No description
npm WARN node No repository field.
npm WARN node No license field.

+ node-red-vis@0.4.2
added 27 packages in 11.974s
```

Any help is appreciated, thanks!

**Comment by aleqcz** [comment]
Is nod-red-vis abandoned? :-( Fingers crossed it's not

**Comment by Abenezer** [comment]
same problem here 
`module.js:472
    throw err;
    ^`
but as a workaround 
**install iobrocker.vis first in the same directory** (Node-red-home) which is ~./node-red in my case 
  ```
   npm install iobroker.vis 
   npm install node-red-vis
```

**Comment by krapas170** [comment]
I have the same problem. When does anybody help here?

**Comment by OptifySudarshanPatil** [comment]
i belive it's abandoned now.
